name = "TrapPack"
author = "HeezQ"
version = "1.0.242"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7028198c34dd3797e0dc8e75199880e020c259b6a6b0e75dacba1a610bef34da"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
