name = "TrapPack"
author = "HeezQ"
version = "1.0.250"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e993092edaee1ea3a9901367a44191f27547e7bd964078b35a26102a68dcd424"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
